services:
  - type: web
    name: taskflow-backend
    plan: free
    runtime: docker
    dockerfilePath: backend/Dockerfile
    dockerContext: backend
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: BETTER_AUTH_SECRET
        sync: false
      - key: FRONTEND_URL
        value: https://taskflow-frontend-talha.vercel.app
      - key: USE_DAPR
        value: "false"
      - key: KAFKA_BOOTSTRAP_SERVERS
        value: ""
      - key: REDIS_URL
        value: ""
    healthCheckPath: /health
