apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "taskflow.fullname" . }}-config
  labels:
    {{- include "taskflow.labels" . | nindent 4 }}
data:
  FRONTEND_URL: {{ .Values.config.frontendUrl | quote }}
  BACKEND_URL: {{ .Values.config.backendUrl | quote }}
  NODE_ENV: {{ .Values.config.nodeEnv | quote }}
  LOG_LEVEL: {{ .Values.config.logLevel | quote }}
