apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "taskflow.fullname" . }}-frontend
  labels:
    {{- include "taskflow.frontend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "taskflow.frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "taskflow.frontend.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.frontend.service.targetPort }}
              protocol: TCP
          env:
            - name: NEXT_PUBLIC_API_URL
              value: "http://localhost:8000"
            - name: NEXT_PUBLIC_APP_URL
              value: "http://localhost:3000"
            - name: NODE_ENV
              value: "{{ .Values.config.nodeEnv }}"
            - name: BETTER_AUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.secretName }}
                  key: {{ .Values.secrets.keys.betterAuthSecret }}
          envFrom:
            - configMapRef:
                name: {{ include "taskflow.fullname" . }}-config
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
          {{- if .Values.frontend.probes.liveness.enabled }}
          livenessProbe:
            tcpSocket:
              port: {{ .Values.frontend.service.targetPort }}
            initialDelaySeconds: {{ .Values.frontend.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.frontend.probes.liveness.periodSeconds }}
            failureThreshold: {{ .Values.frontend.probes.liveness.failureThreshold }}
          {{- end }}
          {{- if .Values.frontend.probes.readiness.enabled }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.frontend.service.targetPort }}
            initialDelaySeconds: {{ .Values.frontend.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.frontend.probes.readiness.periodSeconds }}
            failureThreshold: {{ .Values.frontend.probes.readiness.failureThreshold }}
          {{- end }}
