apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: taskflow
  labels:
    app: taskflow-backend
spec:
  type: ClusterIP
  selector:
    app: taskflow-backend
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
