apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: taskflow
  labels:
    app: taskflow-frontend
spec:
  type: NodePort
  selector:
    app: taskflow-frontend
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
